name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: check cmake version
      run: cmake --version
    - name: configure
      run: cmake -Bbuild -G 'Unix Makefiles'
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
